#!/bin/bash

clear
./configure --x-libraries=/usr/X11R6/lib --x-includes=/usr/X11R6/include --with-tcl-ver=$TCLVER --with-tk-ver=$TKVER --disable-shlib CFLAGS="-framework CoreFoundation"
make
echo "Reconfigured!"
echo "$TCLVER"
echo "$TKVER"
